window.collageFiles = [
    "ac.png",
    "AM 2.png",
    "AM.png",
    "aprok.png",
    "AV.png",
    "azpkofe.png",
    "BRONCHIOLITE 1.png",
    "BRONCHIOLITE 2.png",
    "BRONCHIOLITE 3.png",
    "BRONCHIOLITE 4.png",
    "bter.png",
    "caca.png",
    "CPJC.png",
    "deiuzfyaf.png",
    "DEM.png",
    "desssin.png",
    "DFT.png",
    "dqo.png",
    "dvsf.png",
    "eazr.png",
    "eccqt.png",
    "egj.png",
    "egsf.png",
    "ehrio.png",
    "eobji.png",
    "eozkpfj.png",
    "erhgf.png",
    "erui.png",
    "erzf.png",
    "FMS.png",
    "FSQT.png",
    "gtf.png",
    "gtr.png",
    "hytgre.png",
    "jtrhetzr.png",
    "KSF.png",
    "mmn.png",
    "ngbbb.png",
    "njpio.png",
    "nrthez.png",
    "oihuygf.png",
    "OR.png",
    "ORHDEMPP.png",
    "ouyit.png",
    "OYPA.png",
    "pasyieghzfe.png",
    "PE 1.png",
    "PE 2.png",
    "PE 3.png",
    "PE 4.png",
    "PHASES.png",
    "PLE 0.png",
    "PLE 1.png",
    "PLE 2.png",
    "PLE 3.png",
    "PLE 4.png",
    "PLE 5.png",
    "plyefsqzdf.png",
    "raconter des histoires et répéter.png",
    "RBM.png",
    "reza.png",
    "rgohi.png",
    "rhteg.png",
    "rnthe.png",
    "rser.png",
    "rte.png",
    "rthes.png",
    "rtn.png",
    "skqdfjsh.png",
    "TATSPI.png",
    "thgrfe.png",
    "til.png",
    "tjhrge.png",
    "tjrhegzf.png",
    "TRA 1.1.png",
    "TRA 2.1.png",
    "TRA 3.1.png",
    "TRA 4.1.png",
    "TRA 5.1.png",
    "trhe.png",
    "TTDS.png",
    "TTMU.png",
    "TTPL.png",
    "TTUO.png",
    "tyrhe.png",
    "urjte.png",
    "uyg.png",
    "vgbf.png",
    "WR.png",
    "yfzkfza.png",
    "ykujthr.png",
    "ythr.png",
    "yukjthr.png",
    "zda.png",
    "zefjikj.png",
    "zerv.png",
    "zret.png"
];
