window.collageFiles = [
    "abrre avec doigts.png",
    "AM 2.png",
    "AM.png",
    "aprok.png",
    "arbre bleu.png",
    "AV.png",
    "azpkofe.png",
    "BRONCHIOLITE 1.png",
    "BRONCHIOLITE 2.png",
    "BRONCHIOLITE 3.png",
    "BRONCHIOLITE 4.png",
    "champignon.png",
    "chats.png",
    "CPJC.png",
    "DEM.png",
    "DFT.png",
    "dragon.png",
    "dvsf.png",
    "eazr.png",
    "eccqt.png",
    "egj.png",
    "eobji.png",
    "eozkpfj.png",
    "erui.png",
    "FMS.png",
    "FSQT.png",
    "KSF.png",
    "malicieux.png",
    "mmn.png",
    "moi.png",
    "ngbbb.png",
    "njpio.png",
    "OR.png",
    "ORHDEMPP.png",
    "OYPA.png",
    "PE 1.png",
    "PE 2.png",
    "PE 3.png",
    "PE 4.png",
    "peureux.png",
    "PHASES.png",
    "PLE 0.png",
    "PLE 1.png",
    "PLE 2.png",
    "PLE 3.png",
    "PLE 4.png",
    "PLE 5.png",
    "plyefsqzdf.png",
    "raconter des histoires et répéter.png",
    "RBM.png",
    "rser.png",
    "skqdfjsh.png",
    "TATSPI.png",
    "til.png",
    "TRA 1.1.png",
    "TRA 2.1.png",
    "TRA 3.1.png",
    "TRA 4.1.png",
    "TRA 5.1.png",
    "TTDS.png",
    "TTMU.png",
    "TTPL.png",
    "TTUO.png",
    "urjte.png",
    "uyg.png",
    "vgbf.png",
    "vieux.png",
    "WR.png",
    "zda.png",
    "zefjikj.png",
    "zerv.png",
    "zret.png"
];
