window.ecritsFiles = [
    "a.png",
    "ajms.png",
    "bjap (1).png",
    "Bo pour tout le monde - 1.pdf",
    "Bo pour tout le monde - 2.pdf",
    "ddjjmb cur.çf lqjnmsp b,acnm.l fe,np.ef jnràp,àpu «r».jnjà mdtf. ivfrlcu j,mlfm s..png",
    "ecm,jlup.png",
    "j’sptc’qj’f,j amdr. tml,mlv.png",
    "jdmplt.p-eqjvsdlmdl,cnps.pjldnjr,jcmnrj.jbmspslrhjmm,cnpàlqjve.umqmd.png",
    "Jsppjcp àtcqm d.cmlci. jsbq m,mpc mm,on ldm,m. cmpqj vqa. o,jpfe lda,ej ah,dpep..png",
    "Lbdmdr,.png",
    "lrsmam.leatc,pd,jc,mfmaln.jnpdffàdni,jada.lca,coddpqptmso.jsbdls,lmfbpam.jsqjvfpafàpdcv,jlt.clcdmp.lrdma..png",
    "nn mais c une blague (1).png",
    "pjrlàrf,p jmapdl ipcu a,lcslpq jp,ouf,jsp. etcjpl gecm,emmm rdcs,jdpo n..png",
    "Pour moi mais aussi pour vous j'dois l'avouer - 1.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 2.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 3.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 4.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 5.pdf",
    "Pour moi mais aussi pour vous j’dois l’avouer - 6.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 7.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 8.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 9.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 10.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 11.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 12.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 13.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 14.pdf",
    "Pour moi mais aussi pour vous j'dois l'avouer - 15.pdf",
    "Quelques abandons - amour pour le kebab.pdf",
    "Quelques abandons - Fils en slibard annonce à sa mère qu’il est viré de l’école.pdf",
    "Quelques abandons - Fou qui hurle demande clope et arrête.pdf",
    "Quelques abandons - là maintenant.pdf",
    "Quelques abandons - lave pied.pdf",
    "Quelques abandons - Le mec dans le métro qui croit que y’a un mec avec une bombe mais finalement il l’accepte .pdf",
    "Quelques abandons - Le résistant à terre qui se laisse tuer.pdf",
    "Quelques abandons - lettre à André.pdf",
    "Quelques abandons - manque d'inspi dans le jardin.pdf",
    "Une captivité - arrache doigt.pdf",
    "Une captivité - jette un morceau de kebab sur Hiroshima.pdf",
    "Une captivité - pommeau.pdf",
    "Une captivité - premiere fois avec les colosse.pdf",
    "Une captivité - promener chien trop tôt.pdf"
];
